### ISSUE TITLE
Request for different text size

### ISSUE THREAD

**Issue by alex-soft-r** [robinhood/ticker#54]
Thanks for this lib!!!

Its possible add support for text with different length?
For example, the first word was 8 characters in length, and the second would be 20 characters in length
And when I set the second word, it is drawn outside the 'TickerView'
It is possible to add a function to automatically equalize the text size or transfer a part of the text to the second line?

```
<ScrollView
                            android:id="@+id/svWord"
                            android:layout_width="match_parent"
                            android:layout_height="wrap_content"
                            android:layout_gravity="center">
                   <com.robinhood.ticker.TickerView
                                android:id="@+id/tvWord"
                                android:background="@color/colorPrimary"
                                android:gravity="center"
                                android:layout_width="match_parent"
                                android:layout_height="wrap_content"
                                android:textSize="36sp" />
</ScrollView>
```

**Comment by jinatonic** [comment]
If the new and old text both fit within the maximum bounds of the `TickerView` then there should be no problems.

If the issue is that you want the `TickerView` to automatically resize the text (or overflow to new line) when the text no longer fits in the given bounds. Then this is currently not possible to do. This has been brought up a few times in the past, and the suggestion I provided is simply for you to detect whenever text doesn't fit in a given width yourself and dynamically change the text size on the `TickerView` itself. Or subclass `TickerView` to do that resizing. 

I'll use this ticket to track the work to support this in the library itself, but I can't guarantee when I can get around to it. Feel free to submit PR if you end up investigating this.

**Comment by alex-soft-r** [comment]
Thanks. Ill try to do something by myself. Really cool library!!!
