### ISSUE TITLE
How do all text scroll in one direction?

### ISSUE THREAD

**Issue by tianshaokai** [robinhood/ticker#97]
How do all text scroll in one direction?

**Comment by jinatonic** [comment]
that's currently not supported as the library determines for you the direction to animate in. I can add this feature in the next week or so when I get some free time.

**Comment by tianshaokai** [comment]
Thank you, but I am in urgent need of this function. I hope you can give me some revisions.

**Comment by jinatonic** [comment]
Sorry, I don't have bandwidth to do this until probably the week after since it's Thanksgiving. If you have an urgent need, feel free to fork the library and modify `TickerCharacterList.getCharacterIndices` so that it either always scroll up or scroll down based on the initial start and end indices.

**Comment by tianshaokai** [comment]
The code is a bit complicated and has not been changed successfully.

**Comment by tianshaokai** [comment]
How to reduce the inner margin needed for rolling?

**Comment by jinatonic** [comment]
shoutout to @mattsilber for closing this out.
